name: a11y-cli Test Scan

on:
  push:
    branches: [main]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install a11y-cli
        run: npm install -g git+https://github.com/pprateekk/a11y-cli.git

      - name: Serve HTML and scan
        run: |
          npm install -g serve
          serve . -l 5000 &
          sleep 3
          a11y-cli web-scan http://localhost:5000/index.html --format html --output a11y-report.html

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: a11y-html-report
          path: a11y-report.html
